channels:
  - conda-forge
dependencies:
  - aenum
  - av
  - bokeh >=3.1.1
  - cairosvg
  - coverage
  - customtkinter
  - cython
  - easygui
  - h5py
  - h5py >=3.4.0
  - holoviews >=1.16.2
  - inquirer
  - ipykernel
  - ipyparallel
  - ipython
  - isx
  - jupyter
  - jupyter_bokeh
  - libsvm
  - lxml
  - matplotlib
  - moviepy
  - mypy
  - numpy >=1.26,<2.0.0
  - numpydoc
  - opencv
  - pandas
  - panel >=1.0.2
  - peakutils >=1.3.5
  - pims
  - plotly
  - prettytable
  - psutil
  - pynwb
  - pyqtgraph
  - pytest
  - pytest-cov
  - python <=3.12
  - rasterio
  - rich
  - scikit-image >=0.19.0
  - scikit-learn >=1.2
  - scipy >= 1.10.1
  - seaborn
  - streamlit
  - tensorflow >=2.4.0,<2.16
  - tifffile
  - tk
  - toml
  - tomli
  - tqdm
  - tqdm
  - yapf
  - zarr
